### PR TITLE
Refactor the things

### PR DESCRIPTION
**Pull request by x110dc**
#### What's the plan?
[for PRs that haven't been fully implemented yet]

#### What's this PR do?

There should be very few functional changes, but it changes things under the hood quite a bit:

- Adds a `.dockerignore` and changes `.gitignore`
- Refactors the `Dockerfile` and `Makefile`
- Reformats everything for consistency
- Eliminates `check_response.py`, combines functions in `util.py`
- Upgrades to latest Flask and Celery libraries
- Refactors all of `salesforce.py` (and renames it to `npsp.py`)
- Upgrades the Salesforce API to the latest version (43.0)

#### Why are we doing this? How does it help us?

- It makes development faster (Docker and `Makefile` changes, style consistency); the `Dockerfile` is much simpler now
- Fixes a security issue with the older Flask library
- It rewrites most of the Salesforce interactions and separates the SF concerns from everything else. This should allow easier/quicker development for new features. It simplifies the client code.  It's also the first step in making this a standalone library. This or similar code has been copied to other projects. It would be nice if updates and bug fixes were all in one place.
- Converts use of `print` to `logging` 

#### How should this be manually tested?

1. `make` then `make restart` Try different types of transactions. 

#### Have automated tests been added?

Some added. A lot changed.

#### Has this been tested on mobile?

N/A

#### Are there performance implications?

I don't think so.

#### What are the relevant tickets?

Off-sprint.

#### How should this change be communicated to end users?

Not necessary.

#### Next steps?

- Move `npsp` into a separate package.
- Finish adding support for business memberships.
- Add support for immediate charging.
- Add support for capturing last4 and closed lost reason.

#### Has the relevant documentation/wiki been updated?

Not yet, but I'd like to document the npsp library when it has been completely decoupled.

### CODE REVIEW

**Comment by x110dc** [comment]
- Added `yarn-error.log` to `.dockerignore`
- That's intentional. It probably isn't killing celery because it's running in the background but the next invocation of `make restart` will kill and restart it. Which is what you want most of the time.
- Yeah, oversight on my part. I redid the `Dockerfile.dev` and now that should work.  The `Dockerfile` isn't as nice now but it's still better than it was.

**Comment by x110dc** [comment]
And this branch is on staging too if you want to test there.

**Comment by AndrewGibson27** [comment]
I just made two successful donations on staging, but I'm not seeing them in #stripe. But it looks like yours went through OK last night, so maybe I'm doing something wrong.

As far as `make restart`, I think adding a `& yarn run dev` to the end should do the trick. Right now, since it doesn't return to the shell, there's no way to start up Webpack inside the container.

Thanks for adding in Yarn.

**Comment by x110dc** [comment]
I had to kill `python` too in the `Makefile` or it would continue to run in the background and not allow the next invocation to bind the port. But it should be working now. 

And staging was a configuration issue. Also fixed now.

**Comment by AndrewGibson27** [comment]
Thanks for doing that. All transactions worked for me on staging, so LGTM! I did get this error when donating locally, but I'm sure it's nothing/me being dumb/something wrong with my env.
```
[2018-09-27 15:58:09,657: ERROR/ForkPoolWorker-2] Task app.add_donation[275c8e3f-0c06-471b-a9d5-f53f58a1b966] raised unexpected: SalesforceException('Expected 200 but got 400',)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, intrace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in__protected_call__
    return self.run(*args, **kwargs)
  File "/app/app.py", line 347, in add_donation
    email=email, first_name=first_name, last_name=last_name, zipcode=zipcode
  File "/app/npsp.py", line 540, in get_or_create
    contact = cls.get(email=email)
  File "/app/npsp.py", line 555, in get
    sf = SalesforceConnection() if sf_connection is None else sf_connection
  File "/app/npsp.py", line 52, in __init__
    self.check_response(r)
  File "/app/npsp.py", line 90, in check_response
    raise e
npsp.SalesforceException: Expected 200 but got 400
```

**Comment by AndrewGibson27** [comment]
Just tried again, and the only stuff before that trace is:
```
[2018-09-27 22:46:10,724] INFO in app: ImmutableMultiDict([('installment_period', 'yearly'), ('amount', '35'), ('stripeEmail', 'a@b.com'), ('first_name', 'A'), ('last_name', 'B'), ('reason', ''), ('zipcode', ''), ('installments', 'None'), ('customerId', 'cus_DgVFFoIvNSFcU7'), ('description', 'The Texas Tribune Membership'), ('campaign_id', ''), ('referral_id', ''), ('openended_status', 'Open'), ('pay_fees_value', 'False')])
[2018-09-27 22:46:11,242: INFO/MainProcess] Received task: app.add_donation[f21f47ea-7e8d-469c-ac3e-39c4173874c5]
[2018-09-27 22:46:11,245: INFO/ForkPoolWorker-2] ----Getting contact....
172.17.0.1 - - [27/Sep/2018 22:46:11] "POST /charge HTTP/1.1" 200 -
```

**Comment by AndrewGibson27** [comment]
Credential update worked; LGTM

**Comment by jonathanstegall** [comment]
It looks to me like y'all also removed RabbitMQ. Is that correct, or am I reading wrong?

I ask because I got a notice from Heroku that RabbitMQ is being deleted from all apps, and I'm reading through your changes to see if I can incorporate them into our fork.

> The RabbitMQ-Bigwig team has chosen to discontinue development and operation of this add-on. It will be removed from all apps on 10/31/2018. We advise you to remove it yourself before that date via the Dashboard or the CLI.

**Comment by x110dc** [comment]
No, @jonathanstegall I haven't removed RabbitMQ. I'll be trying an alternate provider in the next few days. I'll let you know how it goes.

**Comment by jonathanstegall** [comment]
@x110dc for what it's worth, I just did a sandbox test in our version using [CloudAMQP](https://elements.heroku.com/addons/cloudamqp). I didn't have to do much:

1. Remove RabbitMQ, add CloudAMQP in its place
2. Change `celery = Celery(app.import_name, broker=app.config['CELERY_BROKER_URL'])` to `celery = Celery(app.import_name, broker=app.config['CLOUDAMQP_URL'])` in `app_celery.py`
3. Update celery to version 4.1.0
4. Add `CLOUDAMQP_URL = os.getenv('CLOUDAMQP_URL')` to `config.py` and `from config import CLOUDAMQP_URL` to `salesforce.py` (I know y'all have refactored this but we haven't yet)
5. Remove `CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')` from `config.py` and `from config import CELERY_BROKER_URL` from `salesforce.py`.

I probably need a tiny bit more testing but this looks solid. It creates customers, opportunities and recurring donations and processes charges.

**Pull request merged**
